name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        container: archlinux
        steps:
            - name: Update packages and install deps
              run: pacman -Syu --noconfirm && pacman -S --noconfirm base-devel git docbook-xsl gperf intltool libmicrohttpd libxslt python-jinja python-lxml quota-tools meson kexec-tools libxkbcommon bash-completion libfido2 rsync bpf clang llvm python-pyelftools libpwquality qrencode lib32-gcc-libs python-pefile
            - name: Clone systemd-chromiumos
              run: git clone https://aur.archlinux.org/systemd-chromiumos.git
            - name: Create a new user
              run: useradd -m builder
            - name: Set permissions
              run: chown -R builder:builder systemd-chromiumos
            - name: Build systemd-chromiumos as builder
              run: sudo -u builder bash -c "cd systemd-chromiumos && makepkg -s --noconfirm && ls"