name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        container: archlinux
        steps:
            - name: Update packages and install deps
              run: pacman -Syu --noconfirm && pacman -S --noconfirm base-devel git
            - name: Clone systemd-chromiumos
              run: git clone https://aur.archlinux.org/systemd-chromiumos.git
            - name: Build systemd-chromiumos
              run: cd systemd-chromiumos && makepkg -s --noconfirm && ls